### ISSUE TITLE
ConsensusStatusEnum 这个枚举类存在问题

### ISSUE THREAD

**Issue by SmileYu** [nuls-io/nuls#19]
NOT_IN(0, 69999),    IN(2, 69998),    WAITING(1, 69997); 这三个枚举值的code 和 
getConsensusStatusByCode（int code）的解析值存在不一致。

public static ConsensusStatusEnum getConsensusStatusByCode(int code) {
        switch (code) {
            case 1:
                return IN;
            case 2:
                return WAITING;
            case 0:
                return NOT_IN;
            default:
                return null;
        }
    }

**Comment by daviyang35** [comment]
Thanks report. We will fix it ASAP.

**Comment by daviyang35** [comment]
Fixed at ee748c8e772091d1a743853c28831d8e900bf744.
