### ISSUE TITLE
模块化是否有必要

### ISSUE THREAD

**Issue by wuzunqian** [nuls-io/nuls#21]
感觉这种模块化的方式像我们公司十几年前的做法， 一个模块一个项目不就行了，还可以用maven来管理，现在的模块都放在一个工程，相互之间没有隔离，相互之间是可以调用到的，开发人员不注意可能依赖就混乱了。模块通过配置文件来约定感觉也不太对，是不是可以抽象一套接口，所有模块按接口去实现就行了。一点想法，可能是我没理解这个项目

**Comment by daviyang35** [comment]
你理解的没问题，因为早期版本改动过于频繁，接口没有稳定，全在一起方便测试。稳定后，接口和实现都会拆分开，并且把接口发布到maven中央仓库。
