### ISSUE TITLE
Use SHA256 instead of MD5

### ISSUE THREAD

**Issue by blockauditech** [nuls-io/nuls#24]
MD5 has long been proven broken and attackers could trigger collisions that eg. allow an incorrect password to have the same hash as the correct password.

@ **nuls-master\rpc-impl\src\main\java\io\nuls\rpc\resources\impl\WalletResouce.java**

```
@POST
    @Path("/imports")
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    @ApiOperation(value = "导入钱包 [3.4.8]")
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "success",response = RpcResult.class)
    })
    public RpcResult importAccountFile(@FormDataParam("file") InputStream in,
                                       @FormDataParam("file") FormDataContentDisposition disposition,
                                       @FormDataParam("password") String password) {
        if (in == null || disposition == null || !StringUtils.validPassword(password)) {
            return RpcResult.getFailed(ErrorCode.PARAMETER_ERROR);
        }
[..............]
String md5 = (String) map.get("password");
        if (keys == null || keys.isEmpty() || StringUtils.isBlank(md5)) {
            return RpcResult.getFailed(ErrorCode.FILE_BROKEN);
        }

        if (!MD5Util.md5(password).equals(md5)) { // ----------------> HERE
            return RpcResult.getFailed(ErrorCode.PASSWORD_IS_WRONG);
        }

        Result result = accountService.importAccounts(keys, password);

        RpcResult rpcResult = new RpcResult(result);

        return rpcResult;
    }
```

You should switch MD5 out for the much more secure SHA256 hashing in Java.

For example...

`MessageDigest digest = MessageDigest.getInstance("SHA-256");`

References:
https://en.wikipedia.org/wiki/Collision_attack
https://nakedsecurity.sophos.com/2016/12/15/yahoo-breach-ive-closed-my-account-because-it-uses-md5-to-hash-my-password/
https://www.mathstat.dal.ca/~selinger/md5collision/
http://www.baeldung.com/sha-256-hashing-java

**Comment by facjas** [comment]
thanks for your advice, 
sha256 is more safer than MD5, and we will change MD5 to sha256.
