### ISSUE TITLE
AccountBaseService.java - Incorrect English translation

### ISSUE THREAD

**Issue by Dennisvm82** [nuls-io/nuls#26]
In _AccountBaseService.java_ the error message on lines **108** and **152** has been incorrectly translated.

**Current message**
 return Result.getFailed(AccountErrorCode.FAILED, "The account not exist, address:" + address);

**Expected message**
 return Result.getFailed(AccountErrorCode.FAILED, "The account **_does_** not exist, address:" + address);

**Comment by daviyang35** [comment]
Thanks for the support. Already processed.
