### ISSUE TITLE
After removing an agent credit is not released

### ISSUE THREAD

**Issue by cpascariello** [nuls-io/nuls#27]
Hey, 
After removing my agent my 20K lockup tokens aren't released.
If you look at the second screenshot you see that the full amount of tokens are still frozen.

Do I need to do something differently?
Cheers

![screen shot 2018-06-25 at 13 34 48](https://user-images.githubusercontent.com/3958216/41848118-ae7e2236-787c-11e8-8d12-ba4631aea1fc.png)

![screen shot 2018-06-25 at 13 38 24](https://user-images.githubusercontent.com/3958216/41848249-1667c3e8-787d-11e8-8b1d-0e4917fa0f9c.png)

**Comment by daviyang35** [comment]
Cancel the consensus node, Mortgage Token will lock for 3 days.
You can check it later.
