### ISSUE TITLE
Logback <MaxFileSize> parameter configuration

### ISSUE THREAD

**Issue by naveen7252** [nuls-io/nuls#33]
I was trying to integrate event module (which I am developing) with Nuls Blockchain but getting Logback related error.

Upon analysis found that MaxFileSize parameter is not valid in the appender as it is "TimeBasedRollingPolicy". We need to use "SizeAndTimeBasedRollingPolicy" rolling policy to use <MaxFileSize> parameter. 

As per official documentation, versions prior to 1.1.7, need  to use "SizeAndTimeBasedFNATP"  to configure MaxFileSize.

I recommend to upgrade the logback version to latest.

I believe with this current configuration, log file is not rolled after reaching 100 MB size.

thanks

**Comment by tag0313** [comment]
Thank you for your suggestion. This problem does exist. We do need the "Size AndTime Based Rolling Policy" tag to take effect. We will delete the file size limit in the new version!

**Comment by naveen7252** [comment]
Thanks for the reply. I will wait for the next release. 
Can somebody from Core team review my module?
https://github.com/naveen7252/event-module

**Comment by niels1286** [comment]
Great job! I will do it.
