### ISSUE TITLE
issue with /api/contract/tx/{hash}  end point in Contract Module

### ISSUE THREAD

**Issue by naveen7252** [nuls-io/nuls#35]
This rest end point is to get Contract transaction by hash, I found below issue in the code.

Module:  Contract-Module
Class name : ContractResource.java
Method : getContractTx() :
Rest EndPoint: /api/contract/tx/{hash}

After retrieving the transaction, Inputs are being calculated from CoinData but these inputs details are not added to ContractTransactionDto (which will be converted to JSON at the end).

Output details are added properly to the ContractTransactionDto.

Also, Calculation of the actual amount of the transaction is depends on above inputs in the method calTransactionValue(txDto); This calculation is not correct unless we add inputs to the ContractTransactionDto before this calculation.

Thanks

**Comment by MIMIEYES** [comment]
Please provide request data for our analysis, THX.

**Comment by naveen7252** [comment]
inputs are being added in the ContractTransactionDto constructor.So it should be fine but I have a doubt why inputs being retrieved again in the method(which are not used) with below code.
// 组装from数据
                    List<Coin> froms = coinData.getFrom();
                    if(froms != null && froms.size() > 0) {
                        byte[] fromHash, owner;
                        int fromIndex;
                        NulsDigestData fromHashObj;
                        Transaction fromTx;
                        Coin fromUtxo;
                        for(Coin from : froms) {
                            owner = from.getOwner();
                            // owner拆分出txHash和index
                            fromHash = LedgerUtil.getTxHashBytes(owner);
                            fromIndex = LedgerUtil.getIndex(owner);
                            // 查询from UTXO
                            fromHashObj = new NulsDigestData();
                            fromHashObj.parse(fromHash,0);
                            fromTx = ledgerService.getTx(fromHashObj);
                            fromUtxo = fromTx.getCoinData().getTo().get(fromIndex);
                            from.setFrom(fromUtxo);
                        }
                    }

Test Data: We could see inputs info here.
http://127.0.0.1:8001/api/contract/tx/00200e3afda28f5bf2c01e0174e95b36ecbe7a4de08cb161f2bdbc7d2f4d70e0946b

**Comment by MIMIEYES** [comment]
Re-query inputs(utxo) just to get its address, because in the transaction, the bytes stored in the owner of inputs are not address, so we need to query the original inputs. 

you can see the logic through the constructor.

**Comment by naveen7252** [comment]
alright..thanks for the clarification
