### ISSUE TITLE
Keystore naming convention

### ISSUE THREAD

**Issue by MechJosh0** [nuls-io/nuls#36]
The exported keystore object properties naming convention have no pattern among them.

See below;
```json
{
  "address": "...",
  "encryptedPrivateKey": "...",
  "alias": "...",
  "pubKey": "...",
  "prikey": "..."
}
```

- `encryptedPrivateKey` = full words / camelCase
- `pubKey` = broken words / camelCase
- `prikey` = broken words / lowercase

I propose the following but only because this is _my_ coding preference:
- `encryptedPrivateKey`
- `publicKey`
- `priviateKey`

I'm not bothered on what convention is decided, as long as one convention is used and not multiple.

**Comment by lichao23** [comment]
Thank you for your suggestions. We are aware of this issue and will accept your suggestions. In the next development, we will follow stricter code specifications.

**Comment by cyberlly** [comment]
Why is the issue close before it is implemented?
