### ISSUE TITLE
GRPC: A high-performance, open-source universal RPC framework.

### ISSUE THREAD

**Issue by donutloop** [nuls-io/nuls#4]
Hi there,
Define your service using Protocol Buffers and then automatically generate idiomatic client and server stubs for your service in a variety of languages and platforms.

Introduction to GRPC: https://www.youtube.com/watch?v=kUz2zjkKxFg
Homepage: https://grpc.io/
Github (Java version): https://github.com/grpc/grpc-java
proto buffers: https://developers.google.com/protocol-buffers/

What do you think about that?

**Comment by facjas** [comment]
thanks for your advice, and we will take it into consideration after development phase.
we will provide stubs, but i am not sure will we use grpc-tools
