### ISSUE TITLE
Merge request / issue queue.

### ISSUE THREAD

**Issue by archfz** [nuls-io/nuls#9]
As I see you guys are pushing code directly without first creating merge requests. MRs are great because you can review your code and others can review them. It is a good practice when working with other people to let them review your changes so that they know better the overall implemented stuff. Also this way all kinds of issues can be detected. 

Also the issues are not on github which I think is again bad. The community should be able to see what your working on, which you set priority. Also this way commits can be linked with issues which again help A LOT.

**Comment by kugeligui** [comment]
I think it is still the development stage, do not need additional branches

**Comment by archfz** [comment]
Yeah but as multiple people work on it they probably have a methodology with which they can work on multiple parallel features. Each task should have it's own branch merged in develop and the removed.

**Comment by kugeligui** [comment]
There is not much development yet, and I believe as more and more people submit, branches will be more and more

**Comment by facjas** [comment]
i agree with archfz, we will keep every commit to show respect to everyone who contributes to the community
